# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import customer_db_pb2 as customer__db__pb2

GRPC_GENERATED_VERSION = '1.78.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in customer_db_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CustomerDBStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StoreUser = channel.unary_unary(
                '/customerdb.CustomerDB/StoreUser',
                request_serializer=customer__db__pb2.StoreUserRequest.SerializeToString,
                response_deserializer=customer__db__pb2.StoreUserResponse.FromString,
                _registered_method=True)
        self.GetUser = channel.unary_unary(
                '/customerdb.CustomerDB/GetUser',
                request_serializer=customer__db__pb2.GetUserRequest.SerializeToString,
                response_deserializer=customer__db__pb2.GetUserResponse.FromString,
                _registered_method=True)
        self.StoreSession = channel.unary_unary(
                '/customerdb.CustomerDB/StoreSession',
                request_serializer=customer__db__pb2.StoreSessionRequest.SerializeToString,
                response_deserializer=customer__db__pb2.StoreSessionResponse.FromString,
                _registered_method=True)
        self.GetSession = channel.unary_unary(
                '/customerdb.CustomerDB/GetSession',
                request_serializer=customer__db__pb2.GetSessionRequest.SerializeToString,
                response_deserializer=customer__db__pb2.GetSessionResponse.FromString,
                _registered_method=True)
        self.UpdateSessionActivity = channel.unary_unary(
                '/customerdb.CustomerDB/UpdateSessionActivity',
                request_serializer=customer__db__pb2.SessionRequest.SerializeToString,
                response_deserializer=customer__db__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.DeleteSession = channel.unary_unary(
                '/customerdb.CustomerDB/DeleteSession',
                request_serializer=customer__db__pb2.SessionRequest.SerializeToString,
                response_deserializer=customer__db__pb2.StatusResponse.FromString,
                _registered_method=True)


class CustomerDBServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StoreUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StoreSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSessionActivity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CustomerDBServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StoreUser': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreUser,
                    request_deserializer=customer__db__pb2.StoreUserRequest.FromString,
                    response_serializer=customer__db__pb2.StoreUserResponse.SerializeToString,
            ),
            'GetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUser,
                    request_deserializer=customer__db__pb2.GetUserRequest.FromString,
                    response_serializer=customer__db__pb2.GetUserResponse.SerializeToString,
            ),
            'StoreSession': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreSession,
                    request_deserializer=customer__db__pb2.StoreSessionRequest.FromString,
                    response_serializer=customer__db__pb2.StoreSessionResponse.SerializeToString,
            ),
            'GetSession': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSession,
                    request_deserializer=customer__db__pb2.GetSessionRequest.FromString,
                    response_serializer=customer__db__pb2.GetSessionResponse.SerializeToString,
            ),
            'UpdateSessionActivity': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSessionActivity,
                    request_deserializer=customer__db__pb2.SessionRequest.FromString,
                    response_serializer=customer__db__pb2.StatusResponse.SerializeToString,
            ),
            'DeleteSession': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSession,
                    request_deserializer=customer__db__pb2.SessionRequest.FromString,
                    response_serializer=customer__db__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'customerdb.CustomerDB', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('customerdb.CustomerDB', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CustomerDB(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StoreUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/customerdb.CustomerDB/StoreUser',
            customer__db__pb2.StoreUserRequest.SerializeToString,
            customer__db__pb2.StoreUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/customerdb.CustomerDB/GetUser',
            customer__db__pb2.GetUserRequest.SerializeToString,
            customer__db__pb2.GetUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StoreSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/customerdb.CustomerDB/StoreSession',
            customer__db__pb2.StoreSessionRequest.SerializeToString,
            customer__db__pb2.StoreSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/customerdb.CustomerDB/GetSession',
            customer__db__pb2.GetSessionRequest.SerializeToString,
            customer__db__pb2.GetSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateSessionActivity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/customerdb.CustomerDB/UpdateSessionActivity',
            customer__db__pb2.SessionRequest.SerializeToString,
            customer__db__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/customerdb.CustomerDB/DeleteSession',
            customer__db__pb2.SessionRequest.SerializeToString,
            customer__db__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
