# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import product_db_pb2 as product__db__pb2

GRPC_GENERATED_VERSION = '1.78.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in product_db_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ProductDBStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterItem = channel.unary_unary(
                '/productdb.ProductDB/RegisterItem',
                request_serializer=product__db__pb2.RegisterItemRequest.SerializeToString,
                response_deserializer=product__db__pb2.RegisterItemResponse.FromString,
                _registered_method=True)
        self.GetItem = channel.unary_unary(
                '/productdb.ProductDB/GetItem',
                request_serializer=product__db__pb2.ItemIdRequest.SerializeToString,
                response_deserializer=product__db__pb2.GetItemResponse.FromString,
                _registered_method=True)
        self.UpdateItemPrice = channel.unary_unary(
                '/productdb.ProductDB/UpdateItemPrice',
                request_serializer=product__db__pb2.UpdateItemPriceRequest.SerializeToString,
                response_deserializer=product__db__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.UpdateItemQuantity = channel.unary_unary(
                '/productdb.ProductDB/UpdateItemQuantity',
                request_serializer=product__db__pb2.UpdateItemQuantityRequest.SerializeToString,
                response_deserializer=product__db__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.GetSellerItems = channel.unary_unary(
                '/productdb.ProductDB/GetSellerItems',
                request_serializer=product__db__pb2.GetSellerItemsRequest.SerializeToString,
                response_deserializer=product__db__pb2.GetItemsResponse.FromString,
                _registered_method=True)
        self.SearchItems = channel.unary_unary(
                '/productdb.ProductDB/SearchItems',
                request_serializer=product__db__pb2.SearchItemsRequest.SerializeToString,
                response_deserializer=product__db__pb2.GetItemsResponse.FromString,
                _registered_method=True)
        self.StoreCart = channel.unary_unary(
                '/productdb.ProductDB/StoreCart',
                request_serializer=product__db__pb2.StoreCartRequest.SerializeToString,
                response_deserializer=product__db__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.GetCart = channel.unary_unary(
                '/productdb.ProductDB/GetCart',
                request_serializer=product__db__pb2.BuyerIdRequest.SerializeToString,
                response_deserializer=product__db__pb2.GetCartResponse.FromString,
                _registered_method=True)
        self.ClearCart = channel.unary_unary(
                '/productdb.ProductDB/ClearCart',
                request_serializer=product__db__pb2.BuyerIdRequest.SerializeToString,
                response_deserializer=product__db__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.AddItemFeedback = channel.unary_unary(
                '/productdb.ProductDB/AddItemFeedback',
                request_serializer=product__db__pb2.AddItemFeedbackRequest.SerializeToString,
                response_deserializer=product__db__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.GetSellerRating = channel.unary_unary(
                '/productdb.ProductDB/GetSellerRating',
                request_serializer=product__db__pb2.GetSellerRatingRequest.SerializeToString,
                response_deserializer=product__db__pb2.GetSellerRatingResponse.FromString,
                _registered_method=True)
        self.MakePurchase = channel.unary_unary(
                '/productdb.ProductDB/MakePurchase',
                request_serializer=product__db__pb2.MakePurchaseRequest.SerializeToString,
                response_deserializer=product__db__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.GetBuyerPurchases = channel.unary_unary(
                '/productdb.ProductDB/GetBuyerPurchases',
                request_serializer=product__db__pb2.BuyerIdRequest.SerializeToString,
                response_deserializer=product__db__pb2.GetBuyerPurchasesResponse.FromString,
                _registered_method=True)


class ProductDBServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateItemPrice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateItemQuantity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSellerItems(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchItems(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StoreCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddItemFeedback(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSellerRating(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MakePurchase(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBuyerPurchases(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProductDBServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterItem': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterItem,
                    request_deserializer=product__db__pb2.RegisterItemRequest.FromString,
                    response_serializer=product__db__pb2.RegisterItemResponse.SerializeToString,
            ),
            'GetItem': grpc.unary_unary_rpc_method_handler(
                    servicer.GetItem,
                    request_deserializer=product__db__pb2.ItemIdRequest.FromString,
                    response_serializer=product__db__pb2.GetItemResponse.SerializeToString,
            ),
            'UpdateItemPrice': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateItemPrice,
                    request_deserializer=product__db__pb2.UpdateItemPriceRequest.FromString,
                    response_serializer=product__db__pb2.StatusResponse.SerializeToString,
            ),
            'UpdateItemQuantity': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateItemQuantity,
                    request_deserializer=product__db__pb2.UpdateItemQuantityRequest.FromString,
                    response_serializer=product__db__pb2.StatusResponse.SerializeToString,
            ),
            'GetSellerItems': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSellerItems,
                    request_deserializer=product__db__pb2.GetSellerItemsRequest.FromString,
                    response_serializer=product__db__pb2.GetItemsResponse.SerializeToString,
            ),
            'SearchItems': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchItems,
                    request_deserializer=product__db__pb2.SearchItemsRequest.FromString,
                    response_serializer=product__db__pb2.GetItemsResponse.SerializeToString,
            ),
            'StoreCart': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreCart,
                    request_deserializer=product__db__pb2.StoreCartRequest.FromString,
                    response_serializer=product__db__pb2.StatusResponse.SerializeToString,
            ),
            'GetCart': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCart,
                    request_deserializer=product__db__pb2.BuyerIdRequest.FromString,
                    response_serializer=product__db__pb2.GetCartResponse.SerializeToString,
            ),
            'ClearCart': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearCart,
                    request_deserializer=product__db__pb2.BuyerIdRequest.FromString,
                    response_serializer=product__db__pb2.StatusResponse.SerializeToString,
            ),
            'AddItemFeedback': grpc.unary_unary_rpc_method_handler(
                    servicer.AddItemFeedback,
                    request_deserializer=product__db__pb2.AddItemFeedbackRequest.FromString,
                    response_serializer=product__db__pb2.StatusResponse.SerializeToString,
            ),
            'GetSellerRating': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSellerRating,
                    request_deserializer=product__db__pb2.GetSellerRatingRequest.FromString,
                    response_serializer=product__db__pb2.GetSellerRatingResponse.SerializeToString,
            ),
            'MakePurchase': grpc.unary_unary_rpc_method_handler(
                    servicer.MakePurchase,
                    request_deserializer=product__db__pb2.MakePurchaseRequest.FromString,
                    response_serializer=product__db__pb2.StatusResponse.SerializeToString,
            ),
            'GetBuyerPurchases': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBuyerPurchases,
                    request_deserializer=product__db__pb2.BuyerIdRequest.FromString,
                    response_serializer=product__db__pb2.GetBuyerPurchasesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'productdb.ProductDB', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('productdb.ProductDB', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProductDB(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/productdb.ProductDB/RegisterItem',
            product__db__pb2.RegisterItemRequest.SerializeToString,
            product__db__pb2.RegisterItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/productdb.ProductDB/GetItem',
            product__db__pb2.ItemIdRequest.SerializeToString,
            product__db__pb2.GetItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateItemPrice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/productdb.ProductDB/UpdateItemPrice',
            product__db__pb2.UpdateItemPriceRequest.SerializeToString,
            product__db__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateItemQuantity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/productdb.ProductDB/UpdateItemQuantity',
            product__db__pb2.UpdateItemQuantityRequest.SerializeToString,
            product__db__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSellerItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/productdb.ProductDB/GetSellerItems',
            product__db__pb2.GetSellerItemsRequest.SerializeToString,
            product__db__pb2.GetItemsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/productdb.ProductDB/SearchItems',
            product__db__pb2.SearchItemsRequest.SerializeToString,
            product__db__pb2.GetItemsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StoreCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/productdb.ProductDB/StoreCart',
            product__db__pb2.StoreCartRequest.SerializeToString,
            product__db__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/productdb.ProductDB/GetCart',
            product__db__pb2.BuyerIdRequest.SerializeToString,
            product__db__pb2.GetCartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/productdb.ProductDB/ClearCart',
            product__db__pb2.BuyerIdRequest.SerializeToString,
            product__db__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddItemFeedback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/productdb.ProductDB/AddItemFeedback',
            product__db__pb2.AddItemFeedbackRequest.SerializeToString,
            product__db__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSellerRating(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/productdb.ProductDB/GetSellerRating',
            product__db__pb2.GetSellerRatingRequest.SerializeToString,
            product__db__pb2.GetSellerRatingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MakePurchase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/productdb.ProductDB/MakePurchase',
            product__db__pb2.MakePurchaseRequest.SerializeToString,
            product__db__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBuyerPurchases(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/productdb.ProductDB/GetBuyerPurchases',
            product__db__pb2.BuyerIdRequest.SerializeToString,
            product__db__pb2.GetBuyerPurchasesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
